version: "3"
services:
  web:
    build: .
    container_name: imgsize_web
    working_dir: /root
    command: gunicorn -c /root/config/gunicorn.conf.py  serve:node
    restart: always
    ports:
      - "8002:8002"
    links:
      - db
    depends_on:
      - db
    env_file:
      - config/env
    volumes:
      - .:/root
    expose:
      - "8002"
  db:
    image: postgres:latest
    container_name: imgsize_db
    restart: always
    env_file:
      - config/env
    ports:
      - '5434:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - "5434"