version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: imgsize_ng
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front:/front
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/site:/etc/nginx/sites-enabled/site
      - ./log:/var/log/nginx
      - ./main/uploads:/uploads
    links:
      - web
    depends_on:
      - web

  web:
    build: ..
    container_name: imgsize_web
    working_dir: /root
    command: gunicorn -c /root/config/gunicorn.conf.py  serve:node
    restart: always
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    env_file:
      - env
    volumes:
      - .:/root
    expose:
      - "5000"
  db:
    image: postgres:latest
    container_name: imgsize_db
    restart: always
    env_file:
      - env
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data